### PR TITLE
Added two new filters, "Priority" and "Due Date"

### PR DESCRIPTION
**Pull request by SahilGoel05**
Added two new filters to the drop down:

Priority:
- Sorts tasks in current category in descending order of priority

Due Date
- Sorts tasks in current category in descending order of due date

Also ran npm prettier:write

Screenshot 2024-06-07 at 3 21 53 AM
Screenshot 2024-06-07 at 3 22 08 AM

### CODE REVIEW

**Comment by SahilGoel05** [comment]
Added .md wikipage to this branch as well

**Comment by HUJOE003** [comment]
Looks great!

**Comment by jhuanny** [comment]
Nice features! Good Work.

**Comment by adigowo** [comment]
Looks awesome!

**Pull request merged**
