### PR TITLE
created priority field

### PR DESCRIPTION
**Pull request by sp14517**
Fixed priority field so that the placeholder says priority with a dropdown of low, medium, high.

### CODE REVIEW

**Comment by jhuanny** [comment]
Looks great! Nice work

**Comment by adigowo** [comment]
Awesome work Sharon, fixed an issue we needed!

**Comment by SahilGoel05** [comment]
Looks good to me! Thanks for fixing this and removing the coverage from git as well.

**Comment by sp14517** [comment]
No changes made to my work as the changes I made to the priority field were necessary for cohesion in our website.

**Pull request merged**
